require 'facets'
desc 'Upload files to ng server'
task 'upload' do
  #Dir.chdir('public') do
    #copy_from = __DIR__ + 'public'
    copy_from = 'public'

    cmd = %~rsync  -rav -e "ssh -p17022  -ljames" #{copy_from}/ neurogami.com:/home/james/webdev/hack.tacio.us/public/ ~
    puts cmd
    sh cmd
  #end
end



